### PR TITLE
switch to stdio as transport fixes #201

### LINKED ISSUE #201: 32Bit Linux VS Code Distributed With libjunixsocket-native-2.0.4.so Built For 64Bit amd64
_From @limey-git on May 5, 2017 12:53_

- VSCode Version: 1.12.0
- OS Version: Ubuntu 12.04 LTS [_**arch=i386**_]

Steps to Reproduce:

1. _[Download and install latest 32 Bit version of vscode for Debian Linux](http://bit.ly/vscode32Bit)_.
2. Launch vscode and install the '_[Language Support for Java(TM) by Red Hat](http://bit.ly/redhatjavaextn)_'  extension.
3. Restart vscode.

On restart, error messages appear; reporting that components required for the '_[Language Support for Java(TM) by Red Hat](http://bit.ly/redhatjavaextn)_' extension, failed to initiate.

_[Reading and analyzing the stacktrace in vscode's log files](https://github.com/Microsoft/vscode/files/978956/library.libjunixsocket-native-2.0.4.so.not.found.0.stacktrace.txt)_, a "_Library 'libjunixsocket-native-2.0.4.so' not found!_" error entry identifies the root cause. That library was tracked down to '[user.home.dir]/.vscode/extensions/redhat.java-0.3.0/server/config_linux/org.eclipse.osgi/45/0/.cp/lib/junixsocket-native-common-2.0.4.jar'.

This is a listing of the native libraries contained in 1.12.0's '_junixsocket-native-common-2.0.4.jar_'...

```
lib/x86_64-MacOSX-gpp/
lib/x86_64-MacOSX-gpp/jni/
lib/x86_64-MacOSX-gpp/jni/history.xml
lib/x86_64-MacOSX-gpp/jni/libjunixsocket-native-2.0.4.dylib
lib/x86_64-MacOSX-gpp/jni/libjunixsocket-native-2.0.4.jnilib
lib/amd64-Linux-gpp/
lib/amd64-Linux-gpp/jni/
lib/amd64-Linux-gpp/jni/libjunixsocket-native-2.0.4.so
lib/amd64-Linux-gpp/jni/history.xml
```
Notice that the only Linux library distributed in the 32Bit 1.12.0 release, is the one built for the amd64 [_**64Bit**_] architecture! It is therefore incompatible with the 32Bit Linux on which 32Bit versions of vscode are meant to be installed.

It was obvious to me after seeing the above files in the 1.12.20 jar, that the system — _knowing that it is running on an i386 OS_ — is attempting to locate a library built for an i386 architecture. But there isn't one  distributed in the 1.12.20 release. Hence the "_Library 'libjunixsocket-native-2.0.4.so' not found!_" error. 

I _[downloaded the junixsocket-parent-2.0.4 source from here](https://github.com/kohlschutter/junixsocket/releases/tag/junixsocket-parent-2.0.4)_ and built it on my 32bit Ubuntu machine, using maven.

I then replaced the original amd64 64Bit '_junixsocket-native-common-2.0.4.jar_' with the 32Bit one that I built _[from the source](http://bit.ly/redhatjavaextn)_. Details of the steps I took _[are listed here](http://bit.ly/javavscode45)_.

On my Ubuntu 12_04 LTS machine, my freshly-built 32Bit [_**i386**_] replacement '_libjunixsocket-native-2.0.4.so_' library and jar files, perfectly resolved _[the defect described in detail here](http://bit.ly/vscodejava45)_.

_Copied from original issue: Microsoft/vscode#26028_

### PR DESCRIPTION
**Pull request by gorkem**

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -61,13 +61,6 @@ export function activate(context: ExtensionContext) {
 				storagePath = getTempWorkspace();
 			}
 			let workspacePath = path.resolve(storagePath + '/jdt_ws');
-			let serverOptions;
-			let port = process.env['SERVER_PORT'];
```
Comment (fbricon) [inline src/extension.ts]: so we lose the ability to debug an existing running server?

**Comment by fbricon** [comment]
unit tests fail

File: src/extension.ts (hunk 1 above)
Comment (gorkem) [inline src/extension.ts]: I will restore this. I missed that we were using SERVER_PORT for it
