### PR TITLE
search all installed JDKs when java.home not specified

### LINKED ISSUE #1621: potential failure of activation when JDK <11 is also installed
### Context
It simply finds the first available JDK in below order:
* java.home
* JDK_HOME
* JAVA_HOME
* fallback to call [node-find-java-home](https://github.com/jsdevel/node-find-java-home#algorithm)

### Steps
Now since it requires JDK 11+, a broken case is:
* both JDK 8 and JDK 11 installed 
* `java.home` not set (for most new users)
* JAVA_HOME points to JDK 8

It will pick JDK 8, and request users to install JDK 11+.

### Possible solution

Add new options to find-java-home, like `minVersion` (requires the library to check version), or request the library to return all possible java homes.

### PR DESCRIPTION
**Pull request by Eskibear**
In macOS Big Sur, `/usr` is wronly recongnized as JDK homedir. See https://github.com/redhat-developer/vscode-java/issues/1700#issuecomment-729478810 

It's caused by defect of upstream lib node-find-java-home. As a hotfix, here I copied a file from https://github.com/microsoft/vscode-java-pack/blob/fc6cb66f496fbbe5e8b2d9971c430e081f5b5460/src/java-runtime/utils/findJavaRuntime.ts

By validating all installed JDKs, this PR can also fix #1621 

Now the JDK detection follows below order: 
* if `java.home` is specified, we validate it, and if it's invalid, we prompt error message as before 
* if `java.home` is not specified, we search all possible places(env.JAVA_HOME, env.PATH, Windows Registry, Common installation directories for popular distributions) for installed JDKs, pick a valid one (major version >= 11) if exists

### CODE REVIEW

**Comment by Eskibear** [comment]
https://github.com/redhat-developer/vscode-java#setting-the-jdk should also be updated in this PR. I'll do that after you review it.

File: src/findJavaRuntimes.ts [hunk 1]
```diff
@@ -0,0 +1,334 @@
...
+ * return metadata for all installed JDKs.
+ */
+export async function findJavaHomes(): Promise<JavaRuntime[]> {
+    const ret: JavaRuntime[] = [];
+    const jdkMap = new Map<string, string[]>();
+
+    updateJDKs(jdkMap, await fromJavaHomeEnv(), "env.JAVA_HOME");
+    updateJDKs(jdkMap, await fromPathEnv(), "env.PATH");
+    updateJDKs(jdkMap, await fromWindowsRegistry(), "WindowsRegistry");
+    updateJDKs(jdkMap, await fromCommonPlaces(), "DefaultLocation");
```
Comment (testforstephen) [inline src/findJavaRuntimes.ts:32]: >The path to the Java Development Kit is searched in the following order:
>- the java.home setting in VS Code settings (workspace then user settings)
>- the JDK_HOME environment variable
>- the JAVA_HOME environment variable
>- on the current system path

This is from our wiki. 

If you could add `updateJDKs(jdkMap, await fromJavaHomeEnv(), "env.JDK_HOME");`, that would be more compatible with the old behavior.

File: src/findJavaRuntimes.ts [hunk 2]
```diff
@@ -0,0 +1,334 @@
...
+        } else {
+            map.set(newJdk, [source]);
+        }
+    }
+}
+
+async function fromJavaHomeEnv(): Promise<string[]> {
+    const ret: string[] = [];
+    if (process.env.JAVA_HOME) {
+        const javaHome = await verifyJavaHome(process.env.JAVA_HOME, JAVAC_FILENAME);
```
Comment (testforstephen) [inline src/findJavaRuntimes.ts:65]: should support process.env.JDK_HOME too.

File: src/requirements.ts [hunk 3]
```diff
@@ -33,9 +34,42 @@ interface ErrorData {
...
+                } else {
+                    msg = `The ${source} (${javaHome}) does not point to a JDK.`;
+                }
+                invalidJavaHome(reject, msg);
+            }
+            javaVersion = await getJavaVersion(javaHome);
+        } else {
+            // java.home not specified, search valid JDKs from env.JAVA_HOME, env.PATH, Registry(Window), Common directories
+            const javaRuntimes = await findJavaHomes();
+            const requiredJdk = javaRuntimes.find(r => r.version >= REQUIRED_JDK_VERSION);
```
Comment (testforstephen) [inline src/requirements.ts:60]: Currently it may return the first JDK randomly, I would prefer to return the first qualified JDK with the source order such as JDK_HOME > JAVA_HOME > System Path > Default Location.

File: src/findJavaRuntimes.ts (hunk 2 above)
Comment (Eskibear) [reply src/findJavaRuntimes.ts]: resolved in https://github.com/redhat-developer/vscode-java/pull/1701/commits/ce0652c541f96fd91e6d3114f5149b1512459bc0

**Review by testforstephen — APPROVED** [review]
LGTM.

@rgrunber @fbricon Since multiple users are reporting Java errors due to wrong JDK detection after upgrading to macOS Big Sur, can we merge this PR into Nov Middle release? WDYT.

**Comment by rgrunber** [comment]
Yes, feel free to merge. We can update release documents afterwards.

**Comment by rgrunber** [comment]
I think there might be an issue with this change that ends up affecting Linux distros.

Have a look at https://github.com/redhat-developer/vscode-java/blob/master/src/findJavaRuntimes.ts#L247
In my case, 'proposed' was '/usr/lib/jvm/java-11-openjdk' . Clearly 'bin/javac' existed to get to this point. What failed for me was the '.isDirectory()' check. On my machine '/usr/lib/jvm/java-11-openjdk' is a symbolic link, so I'd assume the directory check fails.

It's fairly common for symbolic links in /usr/lib/jvm of the form `java-11-openjdk -> java-11-openjdk-11.0.9.11-0.fc32.x86_64`

**Comment by Eskibear** [comment]
Exactly. Let me check if it's safe to simply remove the `isDirectory()` check.

**Comment by Eskibear** [comment]
@rgrunber Is it a convention to install JDKs into `/usr/lib/jvm` ? If so, we can fallback to check this directory on Linux, if no JAVA_HOME specified..

**Comment by Eskibear** [comment]
The `isDirectory()` check was originally added from this commit: https://github.com/jsdevel/node-find-java-home/commit/9bd6daf0461a604d67a4fddc0ae7c36a1e2aae86#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R129

It was not intended to fix any edge case, and I just tried after removing it, no problems found. So I just created a PR to remove it.

**Comment by rgrunber** [comment]
> @rgrunber Is it a convention to install JDKs into `/usr/lib/jvm` ? If so, we can fallback to check this directory on Linux, if no JAVA_HOME specified..

This can vary between distros, so I don't think it holds in call cases, but it could be a good fallback. It's certainly the case for Fedora and Ubuntu.

**Comment by Eskibear** [comment]
@rgrunber ok, I can add `/usr/lib/jvm` as fallback, to increase coverage.
