### PR TITLE
Re-implement smart semicolon detection through text document change API 

### LINKED ISSUE #3290: Smart Semicolon Detection issue with Swiss German Keyboard
When editing a Java file in VS Code using a Swiss German Keyboard I can not enter [ü] or [AltGr]+[ü] (which is left square bracket) because java.edit.smartSemicolonDetection.command is fired. 

##### Environment
- Operating System: Windows 10
- JDK version: 11
- Visual Studio Code version: 1.82.1
- Java extension version: 1.22

##### Steps To Reproduce
1. Open a java file on VS Code using Swiss German Keyboard
2. Try to enter a square bracket, you will get a semicolon

Keybinding logs:

When pressing [ü]:

2023-09-13 17:28:52.958 [info] [KeybindingService]: / Soft dispatching keyboard event
2023-09-13 17:28:52.978 [info] [KeybindingService]: | Resolving ;
2023-09-13 17:28:52.978 [info] [KeybindingService]: \ From 1 keybinding entries, matched java.edit.smartSemicolonDetection.command, when: editorTextFocus && javaLSReady && !editorReadonly && editorLangId == 'java', source: user extension redhat.java.
2023-09-13 17:28:52.978 [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: BracketLeft, keyCode: 186, key: **ü**
2023-09-13 17:28:52.979 [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: BracketLeft, keyCode: 85 (';')
2023-09-13 17:28:52.979 [info] [KeybindingService]: | Resolving ;
2023-09-13 17:28:52.979 [info] [KeybindingService]: \ From 1 keybinding entries, matched java.edit.smartSemicolonDetection.command, when: editorTextFocus && javaLSReady && !editorReadonly && editorLangId == 'java', source: user extension redhat.java.
2023-09-13 17:28:52.979 [info] [KeybindingService]: + Invoking command java.edit.smartSemicolonDetection.command.

When pressing [AltGr]+[ü] (which is "["):

2023-09-13 17:30:36.525 [info] [KeybindingService]: / Soft dispatching keyboard event
2023-09-13 17:30:36.525 [info] [KeybindingService]: \ Keyboard event cannot be dispatched
2023-09-13 17:30:36.525 [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
2023-09-13 17:30:36.525 [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
2023-09-13 17:30:36.525 [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
2023-09-13 17:30:36.525 [info] [KeybindingService]: / Soft dispatching keyboard event
2023-09-13 17:30:36.525 [info] [KeybindingService]: \ Keyboard event cannot be dispatched
2023-09-13 17:30:36.526 [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: AltRight, keyCode: 18, key: AltGraph
2023-09-13 17:30:36.526 [info] [KeybindingService]: | Converted keydown event - modifiers: [alt], code: AltRight, keyCode: 6 ('Alt')
2023-09-13 17:30:36.526 [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
2023-09-13 17:30:36.637 [info] [KeybindingService]: / Soft dispatching keyboard event
2023-09-13 17:30:36.637 [info] [KeybindingService]: | Resolving ;
2023-09-13 17:30:36.637 [info] [KeybindingService]: \ From 1 keybinding entries, matched java.edit.smartSemicolonDetection.command, when: editorTextFocus && javaLSReady && !editorReadonly && editorLangId == 'java', source: user extension redhat.java.
2023-09-13 17:30:36.637 [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: BracketLeft, keyCode: 186, key: **[**
2023-09-13 17:30:36.638 [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: BracketLeft, keyCode: 85 (';')
2023-09-13 17:30:36.638 [info] [KeybindingService]: | Resolving ;
2023-09-13 17:30:36.638 [info] [KeybindingService]: \ From 1 keybinding entries, matched java.edit.smartSemicolonDetection.command, when: editorTextFocus && javaLSReady && !editorReadonly && editorLangId == 'java', source: user extension redhat.java.
2023-09-13 17:30:36.638 [info] [KeybindingService]: + Invoking command java.edit.smartSemicolonDetection.command.
2023-09-13 17:30:36.986 [info] [KeybindingService]: + Storing single modifier for possible chord ctrl.
2023-09-13 17:30:36.987 [info] [KeybindingService]: + Clearing single modifier due to modifier mismatch: ctrl alt

This issue can be fixed manually by adjusting the "Java: Java Smart Semicolon Detection" keyboard shortcut in settings (change keybinding from [ü] to [Shift]+[,] (which is ";") but the default value [ü] makes no sense at all, so this should be fixed.

### PR DESCRIPTION
**Pull request by snjeza**
Fixes #3290

### CODE REVIEW

**Review by rgrunber — CHANGES_REQUESTED** [review]
Can you also confirm your PR restores the `;` behaviour for `java.format.onType` when smart semicolon detection is enabled ? I think this was a regression introduced by the original smart semicolon detection behaviour of overriding the `;` key. Now fixed with this PR.

semicolon-on-type-formatting

File: src/smartSemicolonDetection.ts [hunk 1]
```diff
@@ -6,31 +6,35 @@ import { getJavaConfiguration } from './utils';
...
-					editBuilder.insert(response.position, ";");
-					window.activeTextEditor.selections = [new Selection(response.position, response.position)];
-					newPosition = window.activeTextEditor!.selection.active;
-				});
-				return;
-			}
+	registered = true;
+}
+
+export async function smartSemicolonDetection() {
```
[the remark this answers is not in the document]
Comment (snjeza) [reply src/smartSemicolonDetection.ts:11]: I have update the PR.
`handleTextDocumentchanges` is registered when the server is ready. See https://github.com/redhat-developer/vscode-java/pull/3303/commits/0d2a64e0478d8d7d6252f163c92ec8d8deb671c3#diff-d09bd91ab5c960ab619864434f60b35b363e614f20acb7ef19b898c7bec28ee7R152

File: src/standardLanguageClient.ts [hunk 2]
```diff
@@ -155,6 +149,7 @@ export class StandardLanguageClient {
 					registerDocumentValidationListener(context, this.languageClient);
 					registerCodeCompletionTelemetryListener();
 					commands.executeCommand('setContext', 'javaLSReady', true);
+					context.subscriptions.push(workspace.onDidChangeTextDocument(event => handleTextDocumentChanges(event.document, event.contentChanges)));
```
Comment (rgrunber) [inline src/standardLanguageClient.ts:152]: The problem with moving it here under `ServiceReady` is the text block handling could still work prior to `ServiceReady`. Can't it be left where it was before in extension `activate()` but use `api.serverReady()` to confirm if we should perform the semicolon insertion logic ?

Comment (snjeza) [reply src/standardLanguageClient.ts]: Fixed.

**Review by rgrunber — COMMENTED** [review]
- I would also rename the commit message to something like "Re-implement smart semicolon detection through text document change API"

Looks good overall.

File: src/smartSemicolonDetection.ts [hunk 3]
```diff
@@ -6,31 +6,30 @@ import { getJavaConfiguration } from './utils';
...
-				window.activeTextEditor!.edit(editBuilder => {
-					oldPosition = window.activeTextEditor!.selection.active;
-					editBuilder.insert(response.position, ";");
-					window.activeTextEditor.selections = [new Selection(response.position, response.position)];
-					newPosition = window.activeTextEditor!.selection.active;
-				});
-				return;
-			}
+export async function smartSemicolonDetection() {
+	if (!didSmartSemicolonInsertion() && enabled()) {
```
[the remark this answers is not in the document]
Comment (snjeza) [reply src/smartSemicolonDetection.ts]: I have removed `didSmartSemicolonInsertion`.

**Comment by snjeza** [comment]
> I would also rename the commit message to something like "Re-implement smart semicolon detection through text document change API"

I have updated the PR.

File: src/smartSemicolonDetection.ts [hunk 4]
```diff
@@ -3,56 +3,43 @@
 import { commands, ExtensionContext, Position, Range, Selection, window } from 'vscode';
```
Comment (rgrunber) [inline src/smartSemicolonDetection.ts:3]: `ExtensionContext` can be removed.

File: src/smartSemicolonDetection.ts [hunk 5]
```diff
@@ -3,56 +3,43 @@
...
+		const params: SmartDetectionParams = {
+			uri: window.activeTextEditor.document.uri.toString(),
+			position: window.activeTextEditor!.selection.active,
+		};
+		const response: SmartDetectionParams = await commands.executeCommand(Commands.EXECUTE_WORKSPACE_COMMAND, Commands.SMARTSEMICOLON_DETECTION, JSON.stringify(params));
+		if (response !== null) {
+			window.activeTextEditor!.edit(editBuilder => {
+				const oldPosition = window.activeTextEditor!.selection.active;
+				editBuilder.delete(new Range(new Position(oldPosition.line, oldPosition.character - 1), oldPosition));
+				setActive(true);
```
Comment (rgrunber) [inline src/smartSemicolonDetection.ts:19]: Is the purpose of `setActive` to prevent multiple text change events from entering this block and cause strange behaviour ? If so, would it make more sense to move `setActive` to just before the call to `executeCommand` ?

File: src/smartSemicolonDetection.ts [hunk 6]
```diff
@@ -3,56 +3,43 @@
...
+	if (enabled()) {
+		const params: SmartDetectionParams = {
+			uri: window.activeTextEditor.document.uri.toString(),
+			position: window.activeTextEditor!.selection.active,
+		};
+		const response: SmartDetectionParams = await commands.executeCommand(Commands.EXECUTE_WORKSPACE_COMMAND, Commands.SMARTSEMICOLON_DETECTION, JSON.stringify(params));
+		if (response !== null) {
+			window.activeTextEditor!.edit(editBuilder => {
+				const oldPosition = window.activeTextEditor!.selection.active;
+				editBuilder.delete(new Range(new Position(oldPosition.line, oldPosition.character - 1), oldPosition));
```
Comment (rgrunber) [inline src/smartSemicolonDetection.ts:18]: Is it worth handling this case :

1. User inserts `;` at line 0 column 0 (eg. `|package org.foo`)
2. Immediately after inserting `;`, user hits the <kbd>left</kbd> arrow key moving the cursor from line 0, column 1, to line 0, column 0.

It seems if done quickly, this part of the code uses that updated cursor position.

```
rejected promise not handled within 1 second: Error: Illegal argument: character must be non-negative
extensionHostProcess.js:113
stack trace: Error: Illegal argument: character must be non-negative
	at $ (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10:1101)
	at new n (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:103:4382)
	at /home/rgrunber/git/vscode-java/dist/extension.js:102083:59
	at Object.edit (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:105:53232)
	at /home/rgrunber/git/vscode-java/dist/extension.js:102081:50
	at Generator.next (<anonymous>)
	at fulfilled (/home/rgrunber/git/vscode-java/dist/extension.js:102060:58)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

File: src/smartSemicolonDetection.ts (hunk 4 above)
Comment (snjeza) [reply src/smartSemicolonDetection.ts]: Fixed.

File: src/smartSemicolonDetection.ts (hunk 5 above)
Comment (snjeza) [reply src/smartSemicolonDetection.ts]: Fixed

File: src/smartSemicolonDetection.ts (hunk 6 above)
Comment (snjeza) [reply src/smartSemicolonDetection.ts:19]: I can't reproduce the issue after moving `setActive`.

Comment (rgrunber) [reply src/smartSemicolonDetection.ts:19]: I'm still able to reproduce but it's really a minor issue.
